test:
  adapter: postgresql
  encoding: unicode
  database: solid_spree_test
  pool: 5
  username: 
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: solid_spree_development
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
database: solid_spree_production
  pool: 5
  username: 
  password:
